services:
  document-generation-portal:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: telemed-ia-document-generation-portal:${IMAGE_TAG:-dev}
    container_name: telemed-document-generation-portal-${IMAGE_TAG:-dev}
    ports:
      - "4204:80"
    restart: unless-stopped
