services:
  document-generation-portal:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: telemed-ia-document-generation-portal:latest
    container_name: telemed-document-generation-portal
    ports:
      - "4204:80"
    restart: unless-stopped
