import { InjectionToken } from '@angular/core';

import { ConsultationDocument } from '../model/consultation-document';

/**
 * Port that the document-generation portal uses to fetch its data.
 *
 * In development it is satisfied by SyntheticDocumentService (mock data).
 * In production it will be satisfied by an adapter that calls the
 * document-generation -api through the shell's apiClient.
 */
export interface DocumentDataSource {
  listDocuments(): Promise<readonly ConsultationDocument[]>;

  /**
   * Returns the binary of the PDF for the given document.
   *
   * The mechanism the adapter uses (direct bytes, redirect, object URL,
   * etc.) is not part of this contract. The portal only needs a Blob it
   * can hand to the browser.
   */
  downloadDocument(documentId: string): Promise<Blob>;

  /**
   * Asks the -api to retry the generation of the given document.
   *
   * The idempotencyKey is generated by the caller and reused across
   * retries of the same intention until the operation reaches a terminal
   *    state. Repeating the same key must return the same outcome.
   */
  retryDocument(
    documentId: string,
    idempotencyKey: string,
  ): Promise<ConsultationDocument>;
}

export const DOCUMENT_DATA_SOURCE =
  new InjectionToken<DocumentDataSource>('DOCUMENT_DATA_SOURCE');
