import { InjectionToken } from '@angular/core';

import { ConsultationDocument } from '../model/consultation-document';

/**
 * Port that the document-generation portal uses to fetch its data.
 *
 * In development it is satisfied by SyntheticDocumentService (mock data).
 * In production it will be satisfied by an adapter that calls the
 * document-generation -api through the shell's apiClient.
 */
export interface DocumentDataSource {
  listDocuments(): Promise<readonly ConsultationDocument[]>;

  /**
   * Returns the binary of the PDF. When the real -api lands, this will
   * perform a GET against the presigned URL returned by
   * listDocuments() and resolve with the response body as a Blob.
   */
  downloadDocument(documentId: string): Promise<Blob>;

  /**
   * Asks the -api to retry the generation of the given document.
   *
   * The idempotencyKey is generated by the caller and reused across
   * retries of the same intention until the operation reaches a terminal
   * state. The real -api will treat repeats of the same key as the same
   * request and return the same outcome.
   */
  retryDocument(
    documentId: string,
    idempotencyKey: string,
  ): Promise<ConsultationDocument>;
}

export const DOCUMENT_DATA_SOURCE =
  new InjectionToken<DocumentDataSource>('DOCUMENT_DATA_SOURCE');
